# Generated by Django 4.0.6 on 2022-07-27 15:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Main_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
